server:
  port: 8082

spring:
  application:
    name: student-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/lms_db
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.university.lms: DEBUG
    org.springframework.security: DEBUG