version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: lms-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: lms_db
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lms-network

  admin-service:
    build:
      context: ../admin-service
      dockerfile: Dockerfile
    container_name: lms-admin-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/lms_db?authSource=admin
    networks:
      - lms-network

  student-service:
    build:
      context: ../student-service
      dockerfile: Dockerfile
    container_name: lms-student-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/lms_db?authSource=admin
    networks:
      - lms-network

volumes:
  mongodb_data:

networks:
  lms-network:
    driver: bridge